name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: viniAOliver/viniAOliver@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
